project_id = "uxbdalgkzylmchlapdig"

[functions.interview-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.send-invite-notification]
verify_jwt = false

[functions.login-notification]
verify_jwt = false
